package diso.rabbit.data;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import diso.rabbit.data.Course;
import diso.rabbit.data.Alarm;
import diso.rabbit.data.Day;
import diso.rabbit.data.Schedule;

import diso.rabbit.data.CourseDao;
import diso.rabbit.data.AlarmDao;
import diso.rabbit.data.DayDao;
import diso.rabbit.data.ScheduleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig courseDaoConfig;
    private final DaoConfig alarmDaoConfig;
    private final DaoConfig dayDaoConfig;
    private final DaoConfig scheduleDaoConfig;

    private final CourseDao courseDao;
    private final AlarmDao alarmDao;
    private final DayDao dayDao;
    private final ScheduleDao scheduleDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        courseDaoConfig = daoConfigMap.get(CourseDao.class).clone();
        courseDaoConfig.initIdentityScope(type);

        alarmDaoConfig = daoConfigMap.get(AlarmDao.class).clone();
        alarmDaoConfig.initIdentityScope(type);

        dayDaoConfig = daoConfigMap.get(DayDao.class).clone();
        dayDaoConfig.initIdentityScope(type);

        scheduleDaoConfig = daoConfigMap.get(ScheduleDao.class).clone();
        scheduleDaoConfig.initIdentityScope(type);

        courseDao = new CourseDao(courseDaoConfig, this);
        alarmDao = new AlarmDao(alarmDaoConfig, this);
        dayDao = new DayDao(dayDaoConfig, this);
        scheduleDao = new ScheduleDao(scheduleDaoConfig, this);

        registerDao(Course.class, courseDao);
        registerDao(Alarm.class, alarmDao);
        registerDao(Day.class, dayDao);
        registerDao(Schedule.class, scheduleDao);
    }
    
    public void clear() {
        courseDaoConfig.getIdentityScope().clear();
        alarmDaoConfig.getIdentityScope().clear();
        dayDaoConfig.getIdentityScope().clear();
        scheduleDaoConfig.getIdentityScope().clear();
    }

    public CourseDao getCourseDao() {
        return courseDao;
    }

    public AlarmDao getAlarmDao() {
        return alarmDao;
    }

    public DayDao getDayDao() {
        return dayDao;
    }

    public ScheduleDao getScheduleDao() {
        return scheduleDao;
    }

}
