package diso.rabbit.data;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import diso.rabbit.data.Schedule;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SCHEDULE.
*/
public class ScheduleDao extends AbstractDao<Schedule, Long> {

    public static final String TABLENAME = "SCHEDULE";

    /**
     * Properties of entity Schedule.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property StartHour = new Property(1, java.util.Date.class, "StartHour", false, "START_HOUR");
        public final static Property EndHour = new Property(2, java.util.Date.class, "EndHour", false, "END_HOUR");
        public final static Property IdDay = new Property(3, Long.class, "IdDay", false, "ID_DAY");
        public final static Property IdCourse = new Property(4, Long.class, "IdCourse", false, "ID_COURSE");
    };

    private DaoSession daoSession;

    private Query<Schedule> course_ScheduleListQuery;
    private Query<Schedule> day_ScheduleListQuery;

    public ScheduleDao(DaoConfig config) {
        super(config);
    }
    
    public ScheduleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SCHEDULE' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'START_HOUR' INTEGER NOT NULL ," + // 1: StartHour
                "'END_HOUR' INTEGER," + // 2: EndHour
                "'ID_DAY' INTEGER," + // 3: IdDay
                "'ID_COURSE' INTEGER);"); // 4: IdCourse
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SCHEDULE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Schedule entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getStartHour().getTime());
 
        java.util.Date EndHour = entity.getEndHour();
        if (EndHour != null) {
            stmt.bindLong(3, EndHour.getTime());
        }
 
        Long IdDay = entity.getIdDay();
        if (IdDay != null) {
            stmt.bindLong(4, IdDay);
        }
 
        Long IdCourse = entity.getIdCourse();
        if (IdCourse != null) {
            stmt.bindLong(5, IdCourse);
        }
    }

    @Override
    protected void attachEntity(Schedule entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Schedule readEntity(Cursor cursor, int offset) {
        Schedule entity = new Schedule( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            new java.util.Date(cursor.getLong(offset + 1)), // StartHour
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // EndHour
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // IdDay
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // IdCourse
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Schedule entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setStartHour(new java.util.Date(cursor.getLong(offset + 1)));
        entity.setEndHour(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setIdDay(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setIdCourse(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Schedule entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Schedule entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "scheduleList" to-many relationship of Course. */
    public List<Schedule> _queryCourse_ScheduleList(Long IdCourse) {
        synchronized (this) {
            if (course_ScheduleListQuery == null) {
                QueryBuilder<Schedule> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdCourse.eq(null));
                course_ScheduleListQuery = queryBuilder.build();
            }
        }
        Query<Schedule> query = course_ScheduleListQuery.forCurrentThread();
        query.setParameter(0, IdCourse);
        return query.list();
    }

    /** Internal query to resolve the "scheduleList" to-many relationship of Day. */
    public List<Schedule> _queryDay_ScheduleList(Long IdDay) {
        synchronized (this) {
            if (day_ScheduleListQuery == null) {
                QueryBuilder<Schedule> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdDay.eq(null));
                day_ScheduleListQuery = queryBuilder.build();
            }
        }
        Query<Schedule> query = day_ScheduleListQuery.forCurrentThread();
        query.setParameter(0, IdDay);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDayDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getCourseDao().getAllColumns());
            builder.append(" FROM SCHEDULE T");
            builder.append(" LEFT JOIN DAY T0 ON T.'ID_DAY'=T0.'_id'");
            builder.append(" LEFT JOIN COURSE T1 ON T.'ID_COURSE'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Schedule loadCurrentDeep(Cursor cursor, boolean lock) {
        Schedule entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Day day = loadCurrentOther(daoSession.getDayDao(), cursor, offset);
        entity.setDay(day);
        offset += daoSession.getDayDao().getAllColumns().length;

        Course course = loadCurrentOther(daoSession.getCourseDao(), cursor, offset);
        entity.setCourse(course);

        return entity;    
    }

    public Schedule loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Schedule> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Schedule> list = new ArrayList<Schedule>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Schedule> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Schedule> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
